# Generated by Django 2.0.7 on 2018-07-08 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('Adviser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attention',
            name='maker',
            field=models.ForeignKey(default=users.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
    ]
