# Generated by Django 2.0.7 on 2018-07-11 14:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Adviser', '0002_auto_20180708_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attention',
            new_name='Attitude',
        ),
    ]
