# Generated by Django 2.0.7 on 2018-07-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adviser', '0003_auto_20180711_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attitude',
            name='practiced_rate',
            field=models.FloatField(default=0, verbose_name='実践成功率'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='reason',
            field=models.TextField(max_length=100, verbose_name='心がけて実践すべき端的な理由'),
        ),
    ]
