# Generated by Django 2.0.7 on 2018-07-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adviser', '0004_auto_20180726_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='attitude',
            name='timing',
            field=models.IntegerField(default=0, verbose_name='意識すべきだったタイミング数'),
        ),
        migrations.AddField(
            model_name='attitude',
            name='total_succeeded_point',
            field=models.IntegerField(default=0, verbose_name='累積成功ポイント'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='frequency',
            field=models.FloatField(default=0, verbose_name='意識できた頻度'),
        ),
    ]
